name: TypeScript Checks
description: 'Runs formatting, linting, and tests for TS/JS projects.'
author: 'owen-6936'

branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  node-version:
    description: 'The Node.js version to run the checks'
    required: false
    default: '20'

outputs:
  checks-passed:
    description: 'If all checks passed: format, lint, test'
    value: ${{ steps.verify.outputs.passed }}

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Node.js Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Check for package.json
      run: |
        if [ ! -f package.json ]; then
          echo "❌ No package.json found. This action requires a Node.js project."
          exit 1
        fi
      shell: bash

    - name: Check for required scripts
      run: |
        required_scripts=("format" "lint" "test")

        for script in "${required_scripts[@]}"; do
          if ! jq -e ".scripts[\"$script\"]" package.json > /dev/null; then
            echo "❌ Missing script: \"$script\" in package.json"
            echo "Please define \"$script\" in your package.json to use ts-checks."
            exit 1
          fi
        done
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Format
      run: npm run format
      shell: bash

    - name: Lint
      run: npm run lint
      shell: bash

    - name: Test
      run: npm run test
      shell: bash

    - name: Verify Checks Passed
      id: verify
      if: success()
      run: |
        echo "✅ All checks passed, hurray!"
        echo "passed=true" >> $GITHUB_OUTPUT
      shell: bash

    - name: On Checks Failure
      if: failure()
      run: |
        echo "❌ An error occurred during the checks"
        echo "passed=false" >> $GITHUB_OUTPUT
      shell: bash
